export const FETCH_MENUS = 'FETCH_MENUS';
export const REDUCE_QUANTITY = 'REDUCE_QUANTITY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
